config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get 'myportfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'

  get 'my_friends', to: 'users#my_friends' 
  get 'search_friend', to: 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

  # additional reference to the same table
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friend, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists? 
  end       

  def under_stock_limit?
    stocks.count<10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    else
      "Annonymous"
    end
  end
 
  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def friends_with?(friend)
    self.friend.where(id: friend).exists?
  end
end

  # # check if the friend can be followed
  # # check if the friend already followed
  # def already_followed?(friend_id)
  #   #if not found on the friendship table it means the friend has not been followed
  #   friend.find_by(id: friend_id).present?
  # end

  # def can_follow?(friend_id)
  #   #can follow if the friend not found on the friendship table
  #   !already_followed?(friend_id)
  # end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    # to provide changes to devise function
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def create
        friend = User.find(params[:friend])

        Friendship.create(user_id: current_user.id, friend_id: friend.id) 
        flash[:notice] = "#{friend.email} was successfully added to friend list!"
        
        redirect_to my_friends_path
    end
    
    def destroy
        friend = User.find(params[:id])
        user_friend = Friendship.where(user_id: current_user.id, friend_id: friend.id).first
        user_friend.destroy
        flash[:notice] = "#{friend.email} was successfully removed!"
        redirect_to my_friends_path
    end    
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        # byebug
        
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    # expecting partial js file
                    format.js { render partial: 'users/result/stock' }
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid symbol"
                    format.js { render partial: 'users/result/stock' }
                end
            end 
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter symbol to search"
                format.js { render partial: 'users/result/stock' }
            end
        end
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])

        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save            
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "stock #{stock.name} was successfully added!"
        redirect_to myportfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice] = "#{stock.ticker} was successfully removed!"
        redirect_to myportfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    @tracked_stocks = @user.stocks
  end
  
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friend
  end

  def search
    if params[:friend].present?
      @friends = params[:friend]
      if @friends
        @friends = User.search(params[:friend])
        @friends = current_user.except_current_user(@friends)
        # @friends = current_user.except_current_user(@friends)
        if @friends
          respond_to do |format|
            format.js { render partial: 'users/result/friend' }
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Couldn't find user"
            format.js { render partial: 'users/result/friend' }
          end
        end    
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a friend name or email to search"
          format.js { render partial: 'users/result/friend' }
        end
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-hover mt-3">
            <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col" colspan="2">Action</th>
            </tr>
            </thead>
            <tbody>
                <% @friends.each do |friend|  %>
                <tr>
                    <td><%= friend.email %></td>
                    <td><%= friend.first_name %></td>
                    <td><%= friend.last_name %></td>
                    <td> <%= link_to 'Profile', user_path(friend.id), class: "btn btn-warning" %> </td>
                    <td> <%= link_to 'Delete', friendship_path(friend), method: :DELETE, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/layouts/_messages.html.erb
<!-- <%= flash.each do |type, message| %>
  <div class="alert alert-<%= message == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> -->

<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container container-fluid">
        <%= link_to 'Finance Tracker', root_path, class: "navbar-brand text-white font-lg" %>
        
        <% if current_user %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= 'active' if request.path == myportfolio_path %> ">
                <%= link_to 'My Portfolio', myportfolio_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'My Friend', my_friends_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                    <%= fa_icon 'edit' %> Edit Profile 
                  <% end %>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto text-light">
              <li class="nav-item mr-4">
               <%= fa_icon 'user' %> <%= current_user.full_name %>
              </li>
            </ul>
            <div class="">
              <form class="form-inline my-2 my-lg-0">
                <%= link_to 'Log out', destroy_user_session_path, method: :DELETE, class: "btn btn-danger mr-2" %>
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </div>
        <% end %> 
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container container-fluid">

      <%= render 'layouts/messages' %>
       
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-hover mt-3">
            <thead>
            <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock|  %>
                <tr>
                    <td><%= stock.ticker %></td>
                    <td><%= stock.name %></td>
                    <td><%= stock.last_price %></td>
                    <td> 
                        <% if current_user.can_track_stock?(stock.ticker) %>
                            <%= link_to 'Add to portofolio', user_stocks_path(user: current_user, ticker: stock.ticker.upcase), class: "btn btn-xs btn-success", method: :POST%>
                        <% elsif current_user.id != @user.id%>
                            <span class="badge badge-dark">
                                You are already tracking
                                <% if !current_user.under_stock_limit? %>
                                    10 stocks
                                <% end %>
                                <% if current_user.stock_already_tracked?(stock.ticker) %>
                                    this stock
                                <% end %>
                            </span>
                        <% end %>

                        <% if current_user.id == @user.id %>
                            <%= link_to 'Delete', user_stock_path(stock), method: :DELETE, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> 
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @stock %>
    <div class="card card-header results-block">
        <b>Symbol : </b> <%= @stock.ticker.upcase %>
        <b>Name : </b> <%= @stock.name %>
        <b>Price : </b> <%= @stock.last_price %>
        <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to 'Add to portofolio', user_stocks_path(user: current_user, ticker: @stock.ticker.upcase), class: "btn btn-xs btn-success", method: :POST%>
        <% else %>
            <span class="badge badge-dark">
                You are already tracking
                <% if !current_user.under_stock_limit? %>
                    10 stocks
                <% end %>
                <% if current_user.stock_already_tracked?(@stock.ticker) %>
                    this stock
                <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>Friends List</h1>
<div class="search-area">
    <h4>Search Friends</h4>
    <%= form_tag search_friend_path, method: :get, remote: true do %>
        <div class="form-group row">
            <div class="col-9 no-right-padding">
                <%= text_field_tag :friend, params[:friend], placeholder: "Search name or email...", autofocus: true, class: "form-control form-control-lg input-symbol" %>
            </div>
            <div class="col-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-lg btn-success" do %>
                    <%= fa_icon 'search' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="friend-result"></div>

<% if !@friends.empty? %>
    <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
    <h4>Search Stocks</h4>
    <%= form_tag search_stock_path, method: :get, remote: true do %>
        <div class="form-group row">
            <div class="col-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg input-symbol" %>
            </div>
            <div class="col-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-lg btn-success" do %>
                    <%= fa_icon 'search' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div id="result"></div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% end %>

app/views/users/result/_friend.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @friends %>
    <div class="card card-header results-block mt-2">
        <table class="table">
            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                        <td>
                            <b>Email : </b> <%= friend.email %>
                        </td>
                        <td>
                            <b>Name : </b> <%= "#{friend.first_name} #{friend.last_name}" %>
                        </td>
                        <td>
                            <%= link_to 'View Profile', user_path(friend.id), class: "btn btn-sm btn-warning" %>
                        </td>

                        <td>
                            <% if current_user.friends_with?(friend.id) %>
                                <span class="badge badge-dark">
                                    You are friends
                                </span>
                            <% else %>
                                <%= link_to 'Add to friend list', friendships_path(user: current_user, friend: friend.id), class: "btn btn-sm btn-success", method: :POST%>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>   
        </table>
    </div>
<% end %>

app/views/users/result/_friend.js.erb
document.querySelector('#friend-result').innerHTML = '<%= j render 'users/result/friend.html' %>';

app/views/users/result/_stock.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @stock %>
    <div class="card card-header results-block">
        <b>Symbol : </b> <%= @stock.ticker.upcase %>
        <b>Name : </b> <%= @stock.name %>
        <b>Price : </b> <%= @stock.last_price %>
        <% if current_user.can_track_stock?(@stock.ticker) %>
            <%= link_to 'Add to portofolio', user_stocks_path(user: current_user, ticker: @stock.ticker.upcase), class: "btn btn-xs btn-success", method: :POST%>
            <span class="badge badge-dark">
                You are already tracking
                <% if !current_user.under_stock_limit? %>
                    10 stocks
                <% end %>
                <% if current_user.stock_already_tracked?(@stock.ticker) %>
                    this stock
                <% end %>
            </span>
        <% end %>
    </div>
<% end %>

app/views/users/result/_stock.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'users/result/stock.html' %>';

app/views/users/show.html.erb
<h3>User Details</h3>

<div class="card card-header results-block mt-2">
    <table class="table">
        <tbody>
                <tr>
                    <td>
                        <b>Email : </b> <%= @user.email %>
                    </td>
                    <td>
                        <b>Name : </b> <%= "#{@user.first_name} #{@user.last_name}" %>
                    </td>
                    <td>
                        
                    </td>

                    <td>
                        <% if current_user.friends_with?(@user.id) %>
                            <span class="badge badge-primary">
                                You are friends
                            </span>
                        <% else %>
                            <%= link_to 'Add to friend list', friendships_path(user: current_user, friend: @user.id), class: "btn btn-sm btn-success", method: :POST%>
                        <% end %>
                    </td>
                </tr>
        </tbody>   
    </table>
</div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <p class="lead">This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the app!</h1>

<%= link_to 'Sign out', destroy_user_session_path, method: :DELETE %>